#!/usr/bin/env python3
"""
AJHL API Setup Script
Complete setup for the AJHL Data Collection API
"""

import os
import sys
import subprocess
from pathlib import Path

def check_python_version():
    """Check if Python version is compatible"""
    if sys.version_info < (3, 8):
        print("❌ Python 3.8 or higher is required")
        return False
    print(f"✅ Python {sys.version_info.major}.{sys.version_info.minor} detected")
    return True

def install_requirements():
    """Install Python requirements"""
    print("📦 Installing requirements...")
    try:
        subprocess.run([sys.executable, "-m", "pip", "install", "-r", "ajhl_requirements.txt"], check=True)
        print("✅ Requirements installed successfully")
        return True
    except subprocess.CalledProcessError:
        print("❌ Failed to install requirements")
        return False

def setup_credentials():
    """Setup Hudl credentials"""
    print("🔐 Setting up Hudl credentials...")
    
    if Path("hudl_credentials.py").exists():
        print("✅ Credentials file already exists")
        return True
    
    print("Please enter your Hudl Instat credentials:")
    username = input("Username: ").strip()
    password = input("Password: ").strip()
    
    if not username or not password:
        print("❌ Username and password are required")
        return False
    
    credentials_content = f'''# Hudl Instat Credentials
# Generated by setup script

HUDL_USERNAME = "{username}"
HUDL_PASSWORD = "{password}"
'''
    
    with open("hudl_credentials.py", "w") as f:
        f.write(credentials_content)
    
    print("✅ Credentials file created")
    return True

def setup_api_keys():
    """Setup API keys"""
    print("🔑 Setting up API keys...")
    
    try:
        from ajhl_api_keys import generate_api_key, get_default_api_key
        
        # Generate a default API key
        default_key = get_default_api_key()
        print(f"✅ Default API key generated: {default_key}")
        
        # Save the key to a file for easy access
        with open("api_key.txt", "w") as f:
            f.write(f"Default API Key: {default_key}\n")
            f.write("Use this key in the Authorization header: Bearer {key}\n")
        
        print("📄 API key saved to api_key.txt")
        return True
        
    except Exception as e:
        print(f"❌ Error setting up API keys: {e}")
        return False

def setup_directories():
    """Setup required directories"""
    print("📁 Setting up directories...")
    
    directories = [
        "ajhl_data",
        "ajhl_data/logs",
        "ajhl_data/reports",
        "ajhl_data/opponent_data",
        "ajhl_data/opponent_data/lloydminster_bobcats",
        "ajhl_data/opponent_data/upcoming_opponents",
        "ajhl_data/opponent_data/opponent_analysis"
    ]
    
    for directory in directories:
        Path(directory).mkdir(parents=True, exist_ok=True)
    
    print("✅ Directories created")
    return True

def test_imports():
    """Test if all modules can be imported"""
    print("🧪 Testing imports...")
    
    try:
        import fastapi
        import uvicorn
        import sqlalchemy
        import httpx
        from ajhl_api_system import app
        from ajhl_api_client import AJHLAPIClient
        print("✅ All imports successful")
        return True
    except ImportError as e:
        print(f"❌ Import error: {e}")
        return False

def show_next_steps():
    """Show next steps to the user"""
    print("\n🎉 Setup Complete!")
    print("=" * 50)
    print("Next steps:")
    print("1. Start the API server:")
    print("   python start_api.py")
    print()
    print("2. Or start directly:")
    print("   python ajhl_api_system.py")
    print()
    print("3. Access the API:")
    print("   - API: http://localhost:8000")
    print("   - Docs: http://localhost:8000/docs")
    print("   - Health: http://localhost:8000/health")
    print()
    print("4. Use the API key from api_key.txt in your requests")
    print()
    print("5. Test the API:")
    print("   python -c \"import requests; print(requests.get('http://localhost:8000/health').json())\"")
    print()
    print("📚 For more information, see AJHL_API_DOCUMENTATION.md")

def main():
    """Main setup function"""
    print("🏒 AJHL Data Collection API Setup")
    print("=" * 40)
    
    # Check Python version
    if not check_python_version():
        return False
    
    # Install requirements
    if not install_requirements():
        return False
    
    # Setup credentials
    if not setup_credentials():
        return False
    
    # Setup API keys
    if not setup_api_keys():
        return False
    
    # Setup directories
    if not setup_directories():
        return False
    
    # Test imports
    if not test_imports():
        return False
    
    # Show next steps
    show_next_steps()
    
    return True

if __name__ == "__main__":
    success = main()
    if success:
        print("\n✅ Setup completed successfully!")
    else:
        print("\n❌ Setup failed. Please check the errors above.")
        sys.exit(1)
