"""
Test Mobile Push Notification
Creates a test GitHub issue to verify mobile notifications work
"""

import requests
import os
import json

def create_test_issue():
    """Create a test GitHub issue for mobile notifications"""
    
    # You'll need to create a Personal Access Token
    # Go to GitHub.com → Settings → Developer settings → Personal access tokens → Tokens (classic)
    # Generate new token with 'repo' permissions
    
    token = input("Enter your GitHub Personal Access Token (or press Enter to skip): ").strip()
    if not token:
        print("ℹ️  Skipping test issue creation")
        print("\nTo test manually:")
        print("1. Go to your repository: https://github.com/emilyfehr99/Automated-Post-Game-Reports")
        print("2. Click 'Issues' tab")
        print("3. Click 'New issue'")
        print("4. Title: '🏒 Test Mobile Notification'")
        print("5. Body: 'This is a test to see if you get push notifications on your phone!'")
        print("6. Click 'Submit new issue'")
        return False
    
    # Create test issue
    url = "https://api.github.com/repos/emilyfehr99/Automated-Post-Game-Reports/issues"
    
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json"
    }
    
    data = {
        "title": "🏒 Test Mobile Notification - NHL Predictions",
        "body": """## 📱 Test Mobile Push Notification

This is a test to verify you get push notifications on your phone!

### 🏒 Today's Test Predictions:
1. **SEA @ TOR** - TOR 53.7% (Favorite)
2. **NYR @ MTL** - NYR 51.4% (Favorite)  
3. **MIN @ PHI** - MIN 51.1% (Favorite)
4. **NSH @ WPG** - WPG 51.8% (Favorite)

### 📱 What to Check:
- **Phone notification**: You should get a push notification
- **GitHub app**: Check the app for the notification
- **Home screen**: Notification should appear on your lock screen

### ✅ If You Get This Notification:
The daily predictions will work perfectly! You'll get a new issue every morning at 8 AM CT with today's NHL predictions.

### 🔄 Tomorrow:
A real issue will be created automatically with actual predictions for tomorrow's games.

---
*🤖 Test generated by NHL Prediction System*""",
        "labels": ["nhl-predictions", "test", "mobile-notification"]
    }
    
    try:
        response = requests.post(url, headers=headers, json=data)
        
        if response.status_code == 201:
            issue = response.json()
            print("✅ Test issue created successfully!")
            print(f"🔗 Issue URL: {issue['html_url']}")
            print("📱 Check your phone for a push notification!")
            return True
        else:
            print(f"❌ Error creating issue: {response.status_code}")
            print(response.text)
            return False
            
    except Exception as e:
        print(f"❌ Error: {e}")
        return False

def main():
    """Main test function"""
    print("📱 TESTING MOBILE PUSH NOTIFICATIONS")
    print("=" * 50)
    print("This will create a test GitHub issue to verify mobile notifications work.")
    print("You should get a push notification on your phone!")
    print()
    
    success = create_test_issue()
    
    if success:
        print("\n🎉 TEST COMPLETE!")
        print("Check your phone for a push notification from GitHub!")
        print("If you received it, the daily predictions will work perfectly!")
    else:
        print("\n📝 Manual Test Instructions:")
        print("1. Open GitHub app on your phone")
        print("2. Go to your repository")
        print("3. Create a new issue manually")
        print("4. See if you get a notification")

if __name__ == "__main__":
    main()
