name: Daily NHL Predictions (Simple)

on:
  schedule:
    # Run every day at 8:00 AM Central Time (2:00 PM UTC)
    - cron: '0 14 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  send-predictions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate daily predictions
      run: |
        python3 daily_prediction_notifier.py
        
    - name: Create GitHub Issue with predictions
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          
          // Read the prediction file
          const date = new Date().toISOString().split('T')[0].replace(/-/g, '');
          const filename = `daily_predictions_${date}.txt`;
          
          let predictions = '';
          try {
            predictions = fs.readFileSync(filename, 'utf8');
          } catch (error) {
            predictions = 'No games scheduled for today.';
          }
          
          // Create issue title
          const issueTitle = `🏒 Today's NHL Predictions - ${new Date().toLocaleDateString('en-US', { 
            weekday: 'long', 
            month: 'short', 
            day: 'numeric' 
          })}`;
          
          // Create issue body with predictions
          const issueBody = `## 🏒 Today's NHL Game Predictions
          
          ${predictions}
          
          ---
          *🤖 Generated automatically by NHL Self-Learning Model*
          *📅 ${new Date().toLocaleString('en-US', { timeZone: 'America/Chicago' })} CT*
          
          ### 📱 Mobile Notification
          This issue was created to send you a push notification on your phone with today's predictions!
          
          ### 🎯 How to Use
          - Check the predictions above for today's games
          - The model shows win probabilities and favorites
          - Confidence levels help you understand prediction strength
          
          ### 🔄 Tomorrow
          - A new issue will be created tomorrow with fresh predictions
          - The model learns from today's actual game outcomes
          - Tomorrow's predictions will be more accurate!`;
          
          // Create the issue
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: issueTitle,
            body: issueBody,
            labels: ['nhl-predictions', 'daily', 'mobile-notification']
          });
          
          console.log('✅ GitHub issue created - you should get a push notification on your phone!');
