name: Daily NHL Predictions (Simple)

on:
  schedule:
    # Run every day at 8:00 AM Central Time (2:00 PM UTC)
    - cron: '0 14 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  send-predictions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate daily predictions
      run: |
        python3 daily_prediction_notifier.py
        
    - name: Create notification commit
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Get today's date
        DATE=$(date '+%Y-%m-%d')
        
        # Create a commit with the predictions
        git add daily_predictions_*.txt
        
        if git diff --staged --quiet; then
          echo "No new predictions to commit"
        else
          git commit -m "🏒 Daily NHL Predictions - $DATE

          📊 Today's game predictions generated by the self-learning model.
          
          Check the daily_predictions_*.txt file for full details.
          
          🤖 Generated automatically at $(date '+%Y-%m-%d %H:%M:%S') CT"
          
          git push
          echo "✅ Predictions committed and pushed - you'll get a GitHub notification!"
        fi
