name: daily-nhl-predictions

on:
  schedule:
    # 6am Central: 12:00 UTC (CST, UTC-6) and 11:00 UTC (CDT, UTC-5)
    - cron: '0 12 * * *'
    - cron: '0 11 * * *'
    # Also run at 6:15am Central to catch the window
    - cron: '15 12 * * *'
    - cron: '15 11 * * *'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz requests pandas numpy

      - name: Check time window
        run: |
          python3 -c "
          import pytz
          from datetime import datetime
          ct = pytz.timezone('US/Central')
          now_ct = datetime.now(ct)
          print('Now (CT):', now_ct.strftime('%Y-%m-%d %H:%M:%S %Z'))
          print('Running daily predictions workflow...')
          "

      - name: Run daily predictions
        run: |
          python3 prediction_interface.py


