name: scrape-edge-data

on:
  schedule:
    - cron: '45 12 * * *' # 12:45 UTC daily
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas pytz python-dateutil

      - name: Start log
        run: |
          echo "🏒 DAILY NHL EDGE DATA SCRAPING"
          python - <<'PY'
            from datetime import datetime
            print('📅 Date:', datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S'), 'UTC')
            print('='*50)
          PY

      - name: Scrape Edge data
        run: |
          python3 nhl_clean_repo/daily_edge_data_scraper.py

      - name: Validate output exists
        run: |
          if [ -f "nhl_edge_data.json" ]; then
            echo "✅ Edge data file created successfully"
            ls -l nhl_edge_data.json
          else
            echo "❌ Edge data file not found" && exit 1
          fi

      - name: Commit changes
        run: |
          git config user.email "action@github.com"
          git config user.name "github-actions[bot]"
          git add nhl_edge_data.json
          git diff --cached --quiet || git commit -m "Update NHL Edge data - $(date -u +'%Y-%m-%d')"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update NHL Edge data - ${{ github.run_id }}"
          title: "Update NHL Edge data"
          body: |
            Automated daily update of NHL Edge data used by predictions.
            - Source: Puckalytics Edge report
            - File: nhl_edge_data.json
          branch: chore/update-edge-data
          base: main
          delete-branch: true


